name: Go

on:
  push:
  schedule:
    - cron: "42 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: shardlabs/starknet-devnet:latest
        ports:
          - 5050:5050

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: wait for devnet to be up...
        run: ./.bin/devnet.sh

      - name: Test RPC with mocks
        run: cd rpc && go test -v .

      - name: Preinstall RPC contracts on devnet
        run: cd rpc && go test -timeout 600s -v -env devnet -run TestDeployTransaction . && sleep 5
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "http://localhost:5050/rpc"

      - name: Test RPC on devnet
        run: cd rpc && go test -timeout 600s -v -env devnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "http://localhost:5050/rpc"

      - name: Test RPC on testnet
        run: cd rpc && go test -timeout 600s -v -env testnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "https://starknet-goerli.cartridge.gg/"

      - name: Test RPC with mainnet
        run: cd rpc && go test -timeout 600s -v -env mainnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "https://starknet.cartridge.gg/"

      - name: Test Gateway with testnet
        run: cd gateway && go test -v -env testnet .

      - name: Test Gateway with devnet
        run: cd gateway && go test -v -env devnet .
