name: rpcv02

on:
  push:
    branches:
      - 'feature/rpcv02'  
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: shardlabs/starknet-devnet:latest
        ports:
          - 5050:5050

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: wait for devnet to be up...
        run: ./.bin/devnet.sh

      - name: Preinstall RPC v0.2 contracts on devnet
        run: cd rpcv02 && go test -timeout 600s -v -env devnet -run TestDeployTransaction . && sleep 5
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "http://localhost:5050/rpc"

      - name: Test RPC v0.2 with mocks
        run: cd rpcv02 && go test -v .

      - name: Test RPC v0.2 on devnet
        run: cd rpcv02 && go test -timeout 600s -v -env devnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "http://localhost:5050/rpc"

      - name: Test RPC v0.2 on testnet
        run: cd rpcv02 && go test -timeout 1200s -v -env testnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "https://starknet-goerli.cartridge.gg/"

      - name: Test RPC v0.2 with mainnet
        run: cd rpcv02 && go test -timeout 600s -v -env mainnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          INTEGRATION_BASE: "https://starknet.cartridge.gg/"
